<a href="https://colab.research.google.com/github/justynigam/AIML/blob/main/Assignment_adult.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

df = pd.read_csv("adult.csv")
df.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

**Task 1: Dataset Understanding**

Dataset Shape

In [4]:
df.shape

(32561, 15)

Dataset Information

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

Statistical Summary

In [6]:
df.describe()

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

Class Distribution

In [7]:
df['income'].value_counts()

income
<=50K    24720
>50K      7841
Name: count, dtype: int64

Task 2: Data **Cleaning** **bold text**

In [8]:
import pandas as pd
import numpy as np

Check missing values

In [9]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

Replace "?"

In [10]:
df.replace(' ?', np.nan, inplace=True)

Remove missing rows

In [11]:
df.dropna(inplace=True)

Remove Duplicates Records

In [12]:
df.drop_duplicates(inplace=True)

**Encode Categorical Variables**

In [13]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.select_dtypes(include='object'):
    df[col] = le.fit_transform(df[col])

**Task 3: Feature Engineering**

Separate Feature and Target

In [14]:
X = df.drop("income", axis=1)

y = df["income"]

Train Test Split

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
X, y,
test_size=0.2,
random_state=42
)

Feature scaling

In [16]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

**Task 4: Model Building**

import models

In [17]:
from sklearn.linear_model import LogisticRegression

from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import RandomForestClassifier

from sklearn.neighbors import KNeighborsClassifier

from sklearn.svm import SVC

Create model

In [18]:
models = {

'Logistic Regression': LogisticRegression(max_iter=1000),

'Decision Tree': DecisionTreeClassifier(),

'Random Forest': RandomForestClassifier(),

'KNN': KNeighborsClassifier(),

'SVM': SVC(probability=True)

}

**Task 5: Performance Evaluation**

In [19]:
from sklearn.metrics import accuracy_score

from sklearn.metrics import precision_score

from sklearn.metrics import recall_score

from sklearn.metrics import f1_score

from sklearn.metrics import roc_auc_score

Evaluate

In [20]:
results=[]

for name, model in models.items():

    model.fit(X_train, y_train)

    y_pred=model.predict(X_test)

    y_prob=model.predict_proba(X_test)[:,1]

    results.append([

        name,

        accuracy_score(y_test,y_pred),

        precision_score(y_test,y_pred),

        recall_score(y_test,y_pred),

        f1_score(y_test,y_pred),

        roc_auc_score(y_test,y_prob)

    ])

Display

In [21]:
results_df=pd.DataFrame(results,

columns=["Algorithm",

"Accuracy",

"Precision",

"Recall",

"F1 Score",

"ROC-AUC"])

print(results_df)

             Algorithm  Accuracy  Precision    Recall  F1 Score   ROC-AUC
0  Logistic Regression  0.826214   0.690500  0.463816  0.554900  0.848560
1        Decision Tree  0.809004   0.583484  0.636842  0.608997  0.749155
2        Random Forest  0.860479   0.729730  0.639474  0.681627  0.905758
3                  KNN  0.833743   0.658237  0.599342  0.627410  0.854098
4                  SVM  0.850799   0.742277  0.553289  0.633999  0.890209